version: '3.8'

services:
  narvex-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3200:3200"
    environment:
      - NODE_ENV=production
      - PORT=3200
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3200"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - narvex-network

networks:
  narvex-network:
    driver: bridge